name: go
on: [push, pull_request]
jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.20'
      - name: Run coverage
        run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
      - run: go install golang.org/x/tools/cmd/goimports@latest
      - run: make lint
      - run: make race
