name: go
on: [push, pull_request]
jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.17'
      - uses: codecov/codecov-action@v2.1.0
      - run: go install golang.org/x/tools/cmd/goimports@latest
      - run: make go-get
      - run: make vet
      - run: make imports
      - run: make race
